services:
  - type: web
    name: supportiq-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "true"
      - key: LANGCHAIN_ENDPOINT
        value: "https://api.smith.langchain.com"
      - key: LANGCHAIN_PROJECT
        value: "supportiq"
      - key: PYTHON_VERSION
        value: "3.11.0"
